spring:
  application:
    name: provider
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: false
  instance:
    preferIpAddress: true

com.vnaskos.ids.provider:
  mqttHost: "tcp://${MQTT_HOST:localhost}"
  mqttPort: "${MQTT_PORT:1883}"
  mqttTopic: "${MQTT_TOPIC:provider/test-topic}"
  influxConfig:
    host: "http://${INFLUX_DB_HOST:localhost}:${INFLUX_DB_PORT:8086}"
    database: "${INFLUX_DB_DATABASE:dummysensordata}"
    username: "${INFLUX_DB_USERNAME:}"
    password: "${INFLUX_DB_PASSWORD:}"
    measurement: "${INFLUX_DB_MEASUREMENTS:temperature}"
  fetchDataPeriodicallyEvery: "${FETCH_DATA_EVERY:300}" # SECONDS!!!
