apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
spec:
  selector:
    matchLabels:
      app: provider
  replicas: 1
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - env:
        - name: EUREKA_URI
          value: http://service-registrar:8761/eureka/
        - name: FETCH_DATA_EVERY
          value: "300"
        - name: INFLUX_DB_DATABASE
          value: influx_database
        - name: INFLUX_DB_MEASUREMENTS
          value: temperature
        - name: MQTT_HOST
          value: mqtt-broker
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: topic/default
        image: vnaskos-trusted-ids-connector/data-provider
        imagePullPolicy: Always
        name: provider
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
