version: '3'

networks:
  connector-network:
    driver: bridge

services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p ./data/influxdb
      - ./data/influxdb:/var/lib/influxdb
